# Generated by Django 3.1.7 on 2021-06-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergiesAndDirectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Dr', max_length=20, null=True)),
                ('description', models.CharField(default='Medical Doctor', max_length=20, null=True)),
                ('name', models.CharField(default='Treat Me', max_length=200)),
                ('phone_number', models.CharField(default='08108160545', max_length=20)),
                ('license_number', models.IntegerField(default=1237890, null=True)),
                ('specialty', models.CharField(default='Physician', max_length=200)),
                ('hospital', models.CharField(default='Nairobi Hospital', max_length=200)),
                ('profile_photo', models.ImageField(default='doctor_profiles/no-image.jpg', upload_to='doctor_profiles/')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_cover', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('date_given', models.DateTimeField()),
                ('doctor_prescribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pis.doctor')),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='08108160545', max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='08108160545', max_length=20)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non Binary'), ('O', 'I Prefer not to Say')], max_length=6)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registration_number', models.IntegerField(unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'A+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], max_length=5, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='patients_photo/')),
                ('allergies_and_directives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.allergiesanddirectives')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.doctor')),
                ('medical_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.medicalcover')),
                ('medications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.medicine')),
                ('next_of_kin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pis.nextofkin')),
            ],
            options={
                'ordering': ['-last_modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('consultation_fee', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('recommendations', models.TextField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
