# Generated by Django 3.1.7 on 2021-06-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0002_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pis.nextofkin'),
        ),
    ]
