# Generated by Django 3.1.7 on 2021-06-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0003_auto_20210606_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non Binary'), ('O', 'I Prefer not to Say')], default='MALE', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
