# Generated by Django 3.1.7 on 2021-06-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis', '0004_auto_20210606_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(default=''),
        ),
    ]
